apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "xfs-frag-exporter.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "xfs-frag-exporter.labels" . | nindent 4 }}
